export { BREAKPOINTS } from './breakpoints';
export {
  EMAIL_INVALID_ERROR,
  EMAIL_REQUIRED_ERROR,
  LOGIN_REQUIRED_ERROR,
  NAME_REQUIRED_ERROR,
  PASSWORD_CONFIRMATION_MISMATCH_ERROR,
  PASSWORD_REQUIRED_ERROR,
  PHONE_INCOMPLETE_ERROR,
  REGISTER_PASSWORD_MIN_LENGTH_ERROR,
  RESEND_VERIFICATION_CODE_FAILED_ERROR,
  SPONSOR_INVALID_CREDENTIALS_ERROR,
  SPONSOR_REGISTER_AUTO_LOGIN_FAILED_ERROR,
  SPONSOR_REGISTER_FAILED_ERROR,
  SPONSOR_REGISTER_VALIDATION_ERROR,
  SPONSOR_VERIFY_PHONE_FAILED_ERROR,
  STUDENT_INVALID_CREDENTIALS_ERROR,
  VERIFICATION_CODE_REQUIRED_ERROR
} from './form-errors';
export {
  BACK_LABEL,
  EMAIL_LABEL,
  LOGIN_LABEL,
  NAME_LABEL,
  PASSWORD_CONFIRMATION_LABEL,
  PASSWORD_LABEL,
  PHONE_LABEL,
  RESEND_VERIFICATION_CODE_LABEL,
  RESEND_VERIFICATION_CODE_SUCCESS_MESSAGE,
  SPONSOR_REGISTER_CONTINUE_LABEL,
  SPONSOR_REGISTER_SUBMIT_LABEL,
  SUBMIT_LABEL,
  VERIFICATION_CODE_LABEL
} from './form-labels';
export { PHONE_PLACEHOLDER } from './form-placeholders';
export { PHONE_MASK, PHONE_PATTERN } from './phone';
export { SPONSOR_LOGIN_TAB_LABEL, SPONSOR_REGISTER_TAB_LABEL, STUDENT_LOGIN_TAB_LABEL } from './tab-labels';
